-- Your SQL goes here
CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY,
  first_name VARCHAR(255) NOT NULL,
  last_name VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NULL,
  phone VARCHAR(255) UNIQUE NULL,
  role VARCHAR(255) NOT NULL CHECK (role IN ('OWNER', 'ADMIN', 'USER')),
  password VARCHAR(255) NOT NULL
);
